######################################################################
# Automatically generated by qmake (2.01a) Tue Apr 9 14:18:18 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += main.h
SOURCES += main.cpp
